name: roof_admin_panel
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


    ### Firebase
  # For Firebase initialization. -> https://pub.dev/packages/firebase_core
  firebase_core: ^3.10.0
  # For storing storing nfc tag details. -> https://pub.dev/packages/firebase_database
  firebase_database: ^11.3.0
  # For storing item data in Firestore. -> https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^5.6.1 
  # For Authentication. -> https://pub.dev/packages/firebase_auth
  firebase_auth: ^5.4.0
  # For storing images. -> https://pub.dev/packages/firebase_storage
  firebase_storage: ^12.4.0
  firebase_remote_config: ^5.3.0
  ## State management -> https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: 

  # for easy debugging -> https://pub.dev/packages/logger
  logger: ^2.3.0

  # navigation
  # for navigation -> https://pub.dev/packages/go_router
  go_router: ^14.3.0
  # UI related packages
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  #  https://pub.dev/packages/gap
  gap: ^3.0.1
  # for toast messages -> https://pub.dev/packages/toastification
  toastification: ^2.3.0
  # for skeleton loading -> https://pub.dev/packages/skeletonizer
  skeletonizer: ^1.4.2
  # https://pub.dev/packages/google_fonts
  google_fonts: ^6.2.1
  # for lottie animations -> https://pub.dev/packages/lottie
  lottie: ^3.1.2
  # for markdown support -> https://pub.dev/packages/flutter_markdown 
  flutter_markdown: ^0.7.3+2
  flutter_svg: ^2.0.16
  
  package_info_plus: ^8.1.2
   # for camera usage  -> https://pub.dev/packages/image_picker
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  # for image caching -> https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.4.1
  # for localizations -> https://pub.dev/packages/easy_localization
  easy_localization: ^3.0.7
  mockito: ^5.4.4
  firebase_auth_mocks: ^0.14.1
  email_validator: ^3.0.0
  json_annotation:
  uuid: ^4.5.1
  url_launcher: ^6.3.1

  flutter_animate: ^4.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  flutter_gen_runner:
  very_good_analysis: ^7.0.0

  flutter_lints: ^5.0.0

flutter_gen:
  output:  lib/product/utility/constants/gen/

flutter:
  assets:
      - assets/texts/
      - assets/icons/
      - assets/images/
      - assets/animations/
      - assets/translations/


  uses-material-design: true
