name: Flutter CI

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"

      - name: Setup GitHub Auth for private repos
        run: |
          echo "machine github.com" >> ~/.netrc
          echo "login x-access-token" >> ~/.netrc
          echo "password ${{ secrets.GH_ACCESS_TOKEN }}" >> ~/.netrc

      - name: Install dependencies
        run: flutter pub get

      # - name: Analyze
      #   run: flutter analyze

      # - name: Test
      #   run: flutter test

      - name: Build Web
        run: flutter build web

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
